### ISSUE TITLE
Colocar links de tutoriais das tecnologias utilizadas no projeto.

### ISSUE THREAD

**Issue by amorimmaria** [amorimmaria/TCC-Theme-Ideas#5]
Postar o link de tutoriais com a tecnologia do seu projeto no fórum do Sigaa e colocar no README.md.

**Comment by jainesenna** [comment]
| Links de tutoriais das tecnologias utilizadas no projeto 2020.6
-- | --

- [Curso de NodeJS](https://app.rocketseat.com.br/node/curso-node-js)

- [Curso de ReactJS](https://app.rocketseat.com.br/node/curso-react-js)

- [Introdução ao TypeScript](https://www.devmedia.com.br/introducao-ao-typescript/36729)

- [TypeScript: O guia definitivo](https://medium.com/@oieduardorabelo/typescript-o-guia-definitivo-1a63b04259cc)
